### ISSUE TITLE
Can't remove legacy hooks

### ISSUE THREAD

**Issue by oddMLan** [datitisev/DiscordBot-TrelloDiscordJSRewrite#115]
So apparently there's a new dashboard which can be accessed through the `/setup` command. However when I try to remove any of the legacy hooks, I get a **Not Found** error msg. There's a warning saying it might fail if the repo name changes, but it hasn't changed. I have many repos configured but no matter which one I select I always get the same error.

**Comment by dsevillamartin** [comment]
Sorry about the late response - I only just saw this.

The warning related to the legacy hooks is if you *keep* using them -- if the repo/org is renamed, they'll stop functioning.
That should not affect your ability to remove the legacy hooks from the channel... a quick test locally (after re-setting up my local env) had it working fine.

What gives you a Not Found error -- like the URL? If you don't mind, could you send what url it sends you to so I can better debug this issue?

**Comment by oddMLan** [comment]
https://github.com/user-attachments/assets/53d4f763-c00b-4b00-9e11-38390d770ba0

**Comment by dsevillamartin** [comment]
@oddMLan Hm... thanks for the video. I can only see one place that would cause it to be a 404, which would be the setup id no longer being valid... or maybe the url somehow is just not parsing as it should, even tough i don't know why it'd work locally.

I added some additional messages to the error pages to see if I can narrow it down. Can you let me know what the 404 page says now?

Sorry for having to deal with this. I'm rather confused as the only difference is setup id (all follow same format) and repo name (which is not special as far as I can tell).

**Comment by oddMLan** [comment]
Hi, the 404 page seems to be unchanged. I tried on a private window to make sure it's not a caching issue. 
![image](https://github.com/user-attachments/assets/354656d4-e505-4902-9710-b93cf8178a45)

**Comment by dsevillamartin** [comment]
Welp, I found the issue. Looks to be the NGINX proxy messing with things... converting `%2F` to an actual forward slash.

Didn't manage to fix it in the config so I just made the paths support actual slashes as well. Sorry about that, and thanks for the report! Looks to be working as intended now.

**Comment by oddMLan** [comment]
Thanks, it works now! 🙏

**Comment by oddMLan** [comment]
I'm experiencing the same issue again.
This time, I removed the legacy hook through GitHub itself first. I don't know if that has a anything to do with it?

**Comment by dsevillamartin** [comment]
@oddMLan Hm, the bot doesn't actually know about the legacy hook on GitHub, so that shouldn't matter. Do you have a repo name I could test? Wonder if there are special characters, as looking at my change, it makes the github id match the regex `[\\w\\.\\/]+` so the 404 could be if it doesnt.
