### ISSUE TITLE
<undefined>

### ISSUE THREAD

**Issue by theoparis** [datitisev/DiscordBot-TrelloDiscordJSRewrite#76]
I enabled the webhook and ran G! init repoURL

and it says this
![image](https://user-images.githubusercontent.com/11761863/77949230-72c0c000-727b-11ea-9635-0f473d2d51d5.png)

<undefined>
Isn't it suppoed to show the url or something?
Also, when i run G! conf
it says repo: none
But then i try to reinit it and it says its already initialized

**Comment by theoparis** [comment]
Oh, I forgot to mention I'm using a self-hosted url (GOGS) but the webhook was received in discord so I don't see why it wouldn't be supported.

**Comment by dsevillamartin** [comment]
@creepinson 1) the `repo` setting is for `issue` and `pr` commands
2) GOG might not be using the same webhook data as GitHub for the URL source

**Comment by theoparis** [comment]
Which url source? html_url seems to be there on both. I don't see just url in gogs tho.

**Comment by dsevillamartin** [comment]
I'm not sure what you want me to say. The URL it uses is the `compare` URL, which compares the commits and shows all changes.

https://github.com/YappyBots/YappyGithub/blob/master/Github/Push.js#L47

I won't be making modifications for GOGS - this is a GitHub bot after all.
