### ISSUE TITLE
Features?

### ISSUE THREAD

**Issue by ghost** [datitisev/DiscordBot-TrelloDiscordJSRewrite#79]
This is a really good way to see your progress inside discord but i also say some ways ive seen people do it and it looked really nice. They used the post commit script on git tho. Anyways keep up the good work :D
![Discord_4wsAqe3Oa3](https://user-images.githubusercontent.com/49058911/80286378-ea013c80-86df-11ea-9762-a08998bd5a77.png)

**Comment by dsevillamartin** [comment]
The webhook doesn't provide this info to the bot. It only provides the names of files edited _per commit_.
