### ISSUE TITLE
Unable to config useEmbed to yes

### ISSUE THREAD

**Issue by Desty84** [datitisev/DiscordBot-TrelloDiscordJSRewrite#82]
Config will always revert to "No" and display regular Messages.
In the Gitlab version everything works fine!

![image](https://user-images.githubusercontent.com/8535756/87789992-2efcc100-c840-11ea-8109-d321c676699a.png)

**Comment by dsevillamartin** [comment]
The command only accepts true/false.

I should probably make it accept yes & no as well; I can see why one would think those are the values.

**Comment by Desty84** [comment]
Oh, it worked with Yes in the GL version and since it returned "Success"... alright!
Thank you!
